name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities

version: 3.1.8

homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^2.1.0
  collection: ^1.17.0
  flutter_keyboard_visibility: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
